# Generated by Django 5.2.17 on 2026-09-23 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_teammemberlocation_rls'),
        ('integrations', '0001_initial'),
        ('locations', '0002_location_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=32)),
                ('external_event_id', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead letter'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=16)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='integrations.integration')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='locations.location')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'received_at'], name='ievent_status_recv_idx')],
                'constraints': [models.UniqueConstraint(fields=('integration', 'external_event_id'), name='uniq_integrationevent_integration_external_event')],
            },
        ),
    ]
