# Generated by Django 5.2.17 on 2026-09-30 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_teammemberlocation_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Starter', 'Starter'), ('Growth', 'Growth'), ('Pro', 'Pro'), ('Business', 'Business')], max_length=32)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('quota_requests', models.PositiveIntegerField()),
                ('features_json', models.JSONField(blank=True, null=True)),
                ('provider_plan_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='billing_plan_active_name_uniq'), models.UniqueConstraint(condition=models.Q(('provider_plan_id__isnull', False)), fields=('provider_plan_id',), name='billing_plan_provider_plan_id_uniq'), models.CheckConstraint(condition=models.Q(('monthly_price__gte', 0)), name='billing_plan_monthly_price_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=16)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('payment_provider_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('past_due_at', models.DateTimeField(blank=True, null=True)),
                ('dunning_stage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('provider_status', models.CharField(blank=True, max_length=16, null=True)),
                ('provider_synced_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.merchant')),
                ('pending_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.plan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay')], max_length=16)),
                ('provider_attempt_id', models.CharField(max_length=64)),
                ('attempt_type', models.CharField(choices=[('RENEWAL', 'Renewal'), ('RETRY', 'Retry')], max_length=16)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=16)),
                ('attempted_at', models.DateTimeField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='accounts.merchant')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='billing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('requests_used', models.PositiveIntegerField(default=0)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='accounts.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay')], max_length=16)),
                ('provider_event_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('provider_ref', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_events', to='accounts.merchant')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['merchant'], name='billing_be_unprocessed_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='billing_billingevent_provider_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('merchant',), name='billing_subscription_merchant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_provider_ref__isnull', False)), fields=('payment_provider_ref',), name='billing_subscription_ref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'INCOMPLETE'), models.Q(('current_period_start__isnull', False), ('current_period_end__isnull', False)), _connector='OR'), name='billing_subscription_period_set'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('current_period_end__gt', models.F('current_period_start'))), name='billing_subscription_period_order'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAST_DUE'), ('past_due_at__isnull', False)), models.Q(models.Q(('status', 'PAST_DUE'), _negated=True), ('past_due_at__isnull', True)), _connector='OR'), name='billing_subscription_past_due_at'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dunning_stage__isnull', True), ('past_due_at__isnull', True)), models.Q(('dunning_stage__isnull', False), ('past_due_at__isnull', False)), _connector='OR'), name='billing_subscription_dunning_episode'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('dunning_stage__in', [0, 3, 6])), name='billing_subscription_dunning_stage'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['merchant', 'attempted_at'], name='billing_pa_merchant_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_attempt_id'), name='billing_paymentattempt_provider_uniq'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('provider_attempt_id__startswith', 'pay_')), name='billing_paymentattempt_real_payment'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(fields=('merchant', 'period_start', 'period_end'), name='billing_usagerecord_period_uniq'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='billing_usagerecord_period_order'),
        ),
    ]
