# Generated by Django 5.2.17 on 2026-09-19 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=100, null=True)),
                ('target_id', models.CharField(max_length=64, null=True)),
                ('metadata_json', models.JSONField(null=True)),
                ('actor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='accounts.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='auditlog_au_merchan_f9a4c0_idx')],
            },
        ),
    ]
