# Generated by Django 5.2.17 on 2026-09-23 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_teammemberlocation_rls'),
        ('customers', '0001_initial'),
        ('integrations', '0001_initial'),
        ('locations', '0002_location_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_transaction_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('payment_method', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('VOIDED', 'Voided')], default='COMPLETED', max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customers.customer')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='integrations.integration')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='locations.location')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='accounts.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'occurred_at'], name='txn_merchant_occurred_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'external_transaction_id'), name='uniq_transaction_location_external_txn')],
            },
        ),
    ]
