# Generated by Django 5.2.17 on 2026-09-23 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_teammemberlocation_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('opted_out', models.BooleanField(default=False)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='accounts.merchant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merchant', 'phone'), name='uniq_customer_merchant_phone')],
            },
        ),
    ]
