# Generated by Django 5.2.17 on 2026-09-23 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_teammemberlocation_rls'),
        ('locations', '0002_location_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('petpooja', 'Petpooja'), ('gofrugal', 'GoFrugal'), ('webhook', 'Generic Webhook'), ('csv', 'CSV Import'), ('zapier', 'Zapier'), ('make', 'Make')], max_length=32)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('ERROR', 'Error'), ('DISCONNECTED', 'Disconnected')], default='CONNECTED', max_length=16)),
                ('credentials_encrypted', models.TextField(blank=True, null=True)),
                ('config_json', models.JSONField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrations', to='accounts.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationLocationMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_json', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_mappings', to='integrations.integration')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_mappings', to='locations.location')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.merchant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('integration', 'location'), name='uniq_integrationlocationmapping_integration_location')],
            },
        ),
    ]
