# Generated by Django 5.2.17 on 2026-10-07 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_teammemberlocation_rls'),
        ('locations', '0002_location_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('OWN_NUMBER', 'Own number'), ('SHARED_POOL', 'Shared pool')], max_length=16)),
                ('provider', models.CharField(choices=[('meta_cloud', 'Meta Cloud API')], max_length=16)),
                ('phone_number_id', models.CharField(max_length=64)),
                ('business_account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended')], max_length=16)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_accounts', to='accounts.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppLocationMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_mapping', to='locations.location')),
                ('whatsapp_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_mappings', to='whatsapp.whatsappaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=16)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('provider_template_id', models.CharField(blank=True, max_length=64, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_templates', to='accounts.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'status'], name='whatsapp_tpl_merch_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'name', 'language'), name='whatsapp_template_merchant_name_lang_uniq'), models.UniqueConstraint(condition=models.Q(('provider_template_id__isnull', False)), fields=('provider_template_id',), name='whatsapp_template_provider_id_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappaccount',
            index=models.Index(fields=['merchant'], name='whatsapp_account_merchant_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('merchant__isnull', True), ('sender_type', 'SHARED_POOL')), models.Q(('merchant__isnull', False), ('sender_type', 'OWN_NUMBER')), _connector='OR'), name='whatsapp_account_shared_iff_no_merchant'),
        ),
        migrations.AddConstraint(
            model_name='whatsappaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'phone_number_id'), name='whatsapp_account_provider_phone_uniq'),
        ),
        migrations.AddConstraint(
            model_name='whatsappaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('sender_type', 'SHARED_POOL')), fields=('sender_type',), name='whatsapp_account_single_shared_pool'),
        ),
    ]
