# Generated by Django 5.2.17 on 2026-09-24 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_teammemberlocation_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_hash', models.CharField(max_length=64)),
                ('scopes_json', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.merchant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key_hash',), name='apikeys_apikey_key_hash_uniq')],
            },
        ),
    ]
